export {default as p1} from "../assets/p1.png"
export {default as p2} from "../assets/p2.png"
export {default as p3} from "../assets/p3.png"
export {default as p4} from "../assets/p4.png"
export {default as p5} from "../assets/p5.png"